/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function extractTextFromFile(path: string): string
export declare function extractTextFromFileAsync(path: string): Promise<unknown>
export declare function extractTextFromBuffer(buffer: Buffer): string
export declare function extractTextFromBufferAsync(buffer: Buffer): Promise<unknown>
export declare function init(): void
